mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trends/', include('trends.urls')),
]

trends/urls.py
from django.urls import path
from . import views

app_name = 'trends'

urlpatterns = [
    path('keyword/', views.keyword, name='keyword'),
]

trends/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model):
    name = models.TextField
    created_at = models.DateTimeField(auto_now_add=True)


class Trend(models.Model):
    name = models.TextField
    result = models.IntegerField
    search_period = models.TextField
    created_at = models.DateTimeField(auto_now_add=True)

trends/forms.py
from django import forms
from .models import Keyword, Trend

class KeywordForm(forms.ModelForm):
    class Meta:
        model = Keyword
        fields = ('name', )

trends/views.py
from django.shortcuts import render
from .forms import KeywordForm
from .models import Keyword

# Create your views here.

def keyword(request):
    keyword_form = KeywordForm()
    context = {
        'keyword_from': keyword_form,
    }
    return render(request, 'keyword.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        th {
            background-color: #f2f2f2;
        }
        tr, td{
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
    </style>
</head>
<body>
    <h1>트렌드 분석 애플리케이션</h1>

    <a href="{% url "trends:keyword" %}">키워드 추가</a> |
    <a href="{% url "trends:keyword" %}">크롤링</a> |
    <a href="{% url "trends:keyword" %}">히스토그램</a> |
    <a href="{% url "trends:keyword" %}">지난 1년 크롤링</a> |
    {% block content %}
    {% endblock content %}


</body>
</html>

trends/templates/keyword.html
{% extends "base.html" %}

{% block content %}
<h2>키워드 추가</h2>
<form action="{% url "trends:keyword" %}" method="POST">
    {% csrf_token %}
    <label for="keyword">키워드: </label>
    <input type="text" id="keyword" name="keyword">

    <input type="submit" value='실행하기'>
</form>
<br>
<hr>
<h3>분석을 원하는 키워드 목록</h3>
{% for word in keyword_form %}
    <p> 1번째 키워드 {{ keyword_form.name }} </p>
{% endfor %}


{% endblock content %}